version: "3.9"

networks:
  net_web:
  net_api:
  net_db:
  net_admin:

services:

  nginx:
    image: nginx:alpine
    container_name: brainbox_nginx_dev
    ports:
      - "81:80"
    volumes:
      # ⚠️ dev ใช้ dist ที่ build local
      #- ./frontend/dist/form-mat/browser:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net_web
      - net_api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: brainbox_backend_dev
    expose:
      - "3000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: brainbox_dev
      DB_USER: brainbox
      DB_PASSWORD: 1qaz@WSX
    env_file:
      - ./backend/.env.dev
    networks:
      - net_api
      - net_db
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: brainbox_postgres_dev
    expose:
      - "5432"
    environment:
      POSTGRES_DB: brainbox_dev
      POSTGRES_USER: brainbox
      POSTGRES_PASSWORD: 1qaz@WSX
    volumes:
      - ./database/dev:/var/lib/postgresql/data
    networks:
      - net_db
      - net_admin
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: brainbox_pgadmin_dev
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: aloner8@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1qaz@WSX
    volumes:
      - ./pgadmin/dev:/var/lib/pgadmin
    networks:
      - net_admin
    depends_on:
      - postgres
    restart: unless-stopped
