services:

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: brainbox_nginx_dev
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - backend
    networks:
      - brainbox-net
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: brainbox_backend_dev
    expose:
      - "3000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - postgres
    networks:
      - brainbox-net
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: brainbox_postgres_dev
    volumes:
      - ./database/dev:/var/lib/postgresql/data
    env_file:
      - ./database/.env.dev
    networks:
      - brainbox-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: brainbox_pgadmin_dev
    ports:
      - "127.0.0.1:5050:80"
    env_file:
      - ./pgadmin/.env.dev
    depends_on:
      - postgres
    networks:
      - brainbox-net
    restart: unless-stopped

networks:
  brainbox-net:
