version: "3.9"

networks:
  net_api:
  net_db:
  net_admin:

services:

  nginx:
    build: .
    container_name: brainbox_nginx_dev
    ports:
      - "127.0.0.1:8081:80"
    networks:
      - net_api
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: brainbox_postgres_dev
    volumes:
      - ./database/dev:/var/lib/postgresql/data
    env_file:
      - ./database/.env.dev
    networks:
      - net_db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: brainbox_pgadmin_dev
    ports:
      - "127.0.0.1:5050:80"
    env_file:
      - ./pgadmin/.env.dev
    networks:
      - net_admin
    depends_on:
      - postgres
